apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
  labels:
    app: counting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counting
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: counting
    spec:
      serviceAccountName: counting
      containers:
        - name: counting
          image: hashicorp/counting-service:0.0.2
          ports:
          - containerPort: 9001
            name: http